from app.controllers.user_controller import user_router
from app.controllers.auth_controller import auth_router
from app.controllers.email_controller import email_router
from app.controllers.upload_controller import upload_router